config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'rvngmake_sign_in',
    sign_up: 'rvngmake_sign_up',
    sign_out: 'secret_sign_out',
    password: 'secret_password',
    confirmation: 'secret_confirmation',
    unlock: 'secret_unlock',
    registration: 'secret_registration'
  }
  resources :posts, except: [:index], path: 'blog', param: :slug
  get 'pages/home'
  get 'pages/contact'
  root 'pages#home'
  get 'contact', to: 'pages#contact'
  post 'contact', to: 'messages#create'
  get 'about', to: 'pages#about'
  get 'projects', to: 'pages#projects'
  get 'blog', to: 'posts#index'
  resources :messages, only: [:create], param: :slug
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/message.rb
class Message < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :subject, presence: true
  validates :content, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :content, presence: true, length: { minimum: 10 }
  validates :slug, presence: true

  has_rich_text :content
  has_one_attached :cover_image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def authenticate_admin!
    unless user_signed_in? && current_user.admin?
      flash[:alert] = "Vous devez être administrateur pour accéder à cette page."
      redirect_to root_path
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    @message = Message.new(params.permit(:name, :email, :subject, :content))

    name = params[:name]
    email = params[:email]
    subject = params[:subject]
    message = params[:content]

    ContactMailer.send_contact_email(name, email, subject, message).deliver

    if @message.save
      name = @message.name
      email = @message.email
      subject = @message.subject
      content = @message.content

      MailerRvngMailer.contact_email(name, email, subject, content).deliver_now

      flash[:success] = "Votre message a été envoyé avec succès."
      redirect_to root_path
    else
      flash[:error] = "Une erreur s'est produite lors de l'envoi de votre message. Veuillez réessayer."
      render 'pages/contact'
    end
  end

  private

  def message_params
    params.require(:message).permit(:name, :email, :subject, :content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @latest_posts = Post.order(created_at: :desc).limit(3)
  end

  def contact
    @message = Message.new
  end

  def about
  end

  def projects
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to @post, notice: 'Article créé avec succès'
    else
      render :new, status: :unprocessable_entity, notice: 'Erreur lors de la création de l\'article'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Article modifié avec succès'
    else
      render :edit, status: :unprocessable_entity, notice: 'Erreur lors de la modification de l\'article'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_url, notice: 'Article supprimé avec succès'
  end

  private

  def set_post
    @post = Post.friendly.find(params[:slug])
  end

  def post_params
    params.require(:post).permit(:title, :content, :cover_image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/layouts/_footer.html.erb
<footer>
  <div class="footer-container">
    <div class="contact-info">
      <h4>Contactez-moi</h4>
      <p>Email: <a href="mailto:contact@herveng.com">contact@herveng.com</a></p>
      <p>Téléphone: <a href="tel:+33665511993">+33 6 65 51 19 93</a></p>
    </div>
    <div class="menu">
      <ul>
        <li>
          <%= link_to "Accueil", root_path %>
        </li>
        <li>
          <%= link_to "Projets", projects_path %>
        </li>
        <li>
          <%= link_to "À propos", about_path %>
        </li>
        <li>
          <%= link_to "Contact", contact_path %>
        </li>
      </ul>
    </div>
    <div class="social-icons">
      <div><h4>Suivez-moi</h4></div>
      <div>
        <a href="https://www.linkedin.com/in/herve-nguetsop/" target="_blank" rel="noopener noreferrer" class="social-link">
          <i class="fab fa-linkedin"></i>
        </a>
        <a href="https://github.com/RVNG64" target="_blank" rel="noopener noreferrer" class="social-link">
          <i class="fab fa-github"></i>
        </a>
        <a href="https://www.instagram.com/hervenguetsop/?next=%2F" target="_blank" rel="noopener noreferrer" class="social-link">
          <i class="fab fa-instagram"></i>
        </a>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar">
  <div class="nav-container">
    <div class="nav-logo">
      <div class="logo-container">
        <%= link_to root_path, class: "logo-link" do %>
          <span class="copyright-symbol">&copy;</span>
          <div class="text-wrapper">
            <span class="logo-text">Codé par H.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>
            <span class="hidden-text">Hervé Nguetsop</span>
          </div>
        <% end %>
      </div>
    </div>

    <button class="menu-toggle" aria-label="Menu">
      <span class="burger-bar"></span>
      <span class="burger-bar"></span>
      <span class="burger-bar"></span>
    </button>

    <div class="nav-menu large-screen-menu">
      <ul>
        <li>
          <%= link_to "Accueil", root_path, class: 'nav-link' %>
        </li>
        <li>
          <%= link_to "Projets", projects_path, class: 'nav-link' %>
        </li>
        <li>
          <%= link_to "À propos", about_path, class: 'nav-link' %>
        </li>
<!--        <li>
          <%= link_to "Blog", blog_path %>
        </li>-->
        <li>
          <%= link_to "Say Hello 👋🏿", contact_path, class: 'hello-button' %>
        </li>
      </ul>
    </div>

    <div class="nav-menu small-screen-menu" id="navMenu">
      <ul>
        <li>
          <%= link_to "Accueil", root_path, class: 'nav-link small-screen-link' %>
        </li>
        <li>
          <%= link_to "Projets", projects_path, class: 'nav-link small-screen-link' %>
        </li>
        <li>
          <%= link_to "À propos", about_path, class: 'nav-link small-screen-link' %>
        </li>
<!--        <li>
          <%= link_to "Blog", blog_path %>
        </li>-->
        <li>
          <%= link_to "Contact", contact_path, class: 'nav-link small-screen-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_scrolling_contact.html.erb
<% unless current_page?(contact_path) %>
  <div class="scrolling-container">
    <div class="scrolling-contact">
      <% 10.times do %>
        <%= link_to "Contact me", contact_path , class: "scrolling-link" %>
        <span class="separator">•</span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <title>Hervé Nguetsop - Développeur Web Fullstack & Front-end</title>
    <meta name="keywords" content="développeur web, fullstack, front-end, designer UX/UI, sites web, applications mobiles, Hervé Nguetsop, site internet, wordpress, shopify">
    <meta name="author" content="Hervé Nguetsop">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag 'fav-rv.jpg' %>
    <meta property="og:title" content="Hervé Nguetsop - Développeur Web Fullstack & Front-end" />
    <meta property="og:description" content="Découvrez le site web d'Hervé Nguetsop, développeur web fullstack passionné par le design et le front-end. Spécialisé dans la création de sites web et d'applications modernes et performants." />
    <meta property="og:image" content="<%= asset_url('fav-rv.jpg') %>" />
    <meta property="og:url" content="https://www.herveng.com" />
    <meta property="og:type" content="website" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Hotjar Tracking Code for RVNG -->
    <script>
        (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:3465344,hjsv:6};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');
    </script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'components/intro-home', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="/assets/components/medias.css">
    <link rel="stylesheet" href="/assets/components/navbar.css">
    <link rel="stylesheet" href="/assets/components/home-cards.css">
    <link rel="stylesheet" href="/assets/components/testimonials.css">
    <link rel="stylesheet" href="/assets/components/blog-home.css">
    <link rel="stylesheet" href="/assets/components/header.css">
    <link rel="stylesheet" href="/assets/components/intro-home.css">
    <link rel="stylesheet" href="/assets/components/contact-page.css">
    <link rel="stylesheet" href="/assets/components/projects.css">
    <link rel="stylesheet" href="/assets/components/about.css">
    <link rel="stylesheet" href="/assets/components/posts_new.css">
    <link rel="stylesheet" href="/assets/components/posts_show.css">
    <link rel="stylesheet" href="/assets/components/posts_index.css">
    <link rel="stylesheet" href="/assets/components/posts_edit.css">
    <link rel="stylesheet" href="/assets/components/cursor.css">
    <link rel="stylesheet" href="/assets/stylesheets/application.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Sora:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <%= javascript_importmap_tags %>

    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/swiper/swiper-bundle.min.css" />
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aos@2.3.1/dist/aos.css" />
    <script defer src="https://cdn.jsdelivr.net/npm/aos@2.3.1/dist/aos.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <%= javascript_pack_tag "application", 'data-turbo-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <%= yield %>
    <%= render "layouts/scrolling_contact" %>
    <%= render "layouts/footer" %>
    <%= render "layouts/audioplayer" %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/ScrollMagic.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/plugins/debug.addIndicators.min.js"></script>
<!--    <% if user_signed_in? %>
      <%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'Se connecter', new_user_session_path %>
      <%= link_to 'S\'inscrire', new_user_registration_path %>
    <% end %>
-->
  </body>
</html>

app/views/messages/create.html.erb
<h1>Messages#create</h1>
<p>Find me in app/views/messages/create.html.erb</p>

app/views/pages/about.html.erb
<header class="about-header">
  <video autoplay muted loop id="video-about">
    <source src="https://res.cloudinary.com/dvzsvgucq/video/upload/v1679239423/FREE_4K_Light_Leak_o8bz1x.mp4" type="video/mp4">
    Votre navigateur ne supporte pas la lecture de vidéos HTML5.
  </video>
  <h1>Imaginer. Créer. <br> Et faire vivre votre univers.</h1>
</header>

<div class="about-content">
  <section class="about-parallax-section" id="about-section1">
      <h2>Développeur FullStack <br> Passionné par le design</h2>
  </section>
  <section class="about-detail-section">
      <div class="text-container">
        <h2>Développeur Web Fullstack</h2>
        <p>Je découvre le développement informatique durant mon aventure startup 2021, que je pratique d'abord
        en auto-didacte avant d'obtenir un diplôme et devenir Développeur FullStack avec le Wagon,
        bootcamp de développement informatique n°1 au Monde.</p>
        <p>Mais je suis passé par beaucoup d'expériences différentes avant de devenir développeur...</p>
      </div>
      <div class="image-container">
          <img src="https://res.cloudinary.com/dvzsvgucq/image/upload/v1680248130/default_meta_image_i9u1iu.jpg" alt="Le Wagon">
      </div>
  </section>

  <section class="about-parallax-section" id="about-section2">
    <h2>Ecole de Commerce à Lille</h2>
  </section>
  <section class="about-detail-section">
    <div class="text-container">
        <h2>Master à l'EDHEC Business School (BBA)</h2>
        <p>Originaire du Pays Basque, je passe mon Master à l'EDHEC Lille et 8 mois d'échange universitaire aux Philippines</p>
    </div>
    <div class="image-container">
        <img src="https://res.cloudinary.com/dvzsvgucq/image/upload/v1680026655/BBA_Accueil_header_1_M6_0_jk8uhs.jpg" alt="EDHEC">
    </div>
  </section>

  <section class="about-parallax-section" id="about-section3">
      <h2>Premières expériences professionnelles</h2>
  </section>
  <section class="about-detail-section">
      <div class="text-xp">
        <h2>Evénementiel, Serge Betsen, Consultant...</h2>
        <p>Anecdote: En tant que consultant de Serge Betsen dans toutes ses activités, ma première recommandation
        fut d'entamer la rédaction d'un livre afin d'exposer sa vision le rugby français. Après avoir trouvé l'éditeur,
        et managé le projet de bout en bout, le livre sort à la FNAC et tous les libraires de France, un an et demi plus tard : <i>"Les 7 plaies du rugby français"</i>.</p>
      </div>
      <div class="image-xp">
          <img src="https://res.cloudinary.com/dvzsvgucq/image/upload/v1680025932/Nike_-_Smoocyclette_-_CM_f%C3%A9minine_qozjeg.jpg" alt="Nike Smoocyclette" >
      </div>
  </section>

  <section class="about-parallax-section" id="about-section4">
      <h2>Startup</h2>
  </section>
  <section class="about-detail-section">
    <div class="text-container">
      <h2>La Smoocyclette fait le tour des médias</h2>
      <p>Je créé en 2017 la Smoocyclette, un vélo qui permet de faire des smoothies en pédalant. Une animation événementielle
      qui trouve très vite son public et fait le tour de France mais aussi à l'étranger : Espagne, Italie, Luxembourg, Belgique, Andorre...
      Mais aussi le tour des plus grands médias nationaux et internationaux : Forbes, la BBC, TV5 Monde, L'Equipe, M6, Quotidien de Yann Barthès, Elle Espagne, et bien d'autres...
      Quelques références: Porsche, Air France, Nike, la FFF, la Fashion Week, Le Tour de France...
      <p>Société revendue en  2022.</p>
      </p>
      <div class="about-media-logos">
        <img src="https://logos-marques.com/wp-content/uploads/2022/03/Forbes-logo.png" alt="Forbes" />
        <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/BBC_Logo_2021.svg/1200px-BBC_Logo_2021.svg.png" id="bbc" alt="BBC" />
        <img src="https://upload.wikimedia.org/wikipedia/commons/4/4a/L%27Equipe_logo.png" alt="L'Équipe" />
        <img src="https://upload.wikimedia.org/wikipedia/fr/0/01/Logo-Quotidien-Saison-6.png" alt="Quotidien de Yann Barthès" />
        <img src="https://upload.wikimedia.org/wikipedia/commons/5/51/Logo_TV5_Monde_-_2021.svg" alt="TV5 Monde" />
        <img src="https://dirigeants-entreprise.com/content/uploads/M6.png" alt="M6" />
        <img src="https://upload.wikimedia.org/wikipedia/commons/5/53/France_2_2018.svg" id="fr2" alt="France 2" />
      </div>
    </div>
    <div class="image-container">
      <img src="https://res.cloudinary.com/dvzsvgucq/image/upload/v1682877944/tz-autour-du-v195169lo-1-compressed_zszysx.webp" alt="Autour du vélo Gérard Holtz">
    </div>
  </section>

  <section class="about-parallax-section" id="about-section5">
      <h2>Photographe</h2>
  </section>
  <section class="about-detail-section">
    <div class="text-container">
      <h2>Photographe professionnel</h2>
      <p>Photographe depuis 2021 pour les théâtres de la Scène Nationale</p>
      <div class="intro-button">
        <a href="https://portfolio-photo.herokuapp.com/" target="_blank" class="insta-btn">Voir quelques photos</a>
      </div>
    </div>
    <div class="image-container">
        <img src="https://res.cloudinary.com/dvzsvgucq/image/upload/v1682877944/singer_1__wiitrw.webp" alt="Troupe Alaia singer">
    </div>
  </section>
</div>

app/views/pages/contact.html.erb
<div class="contact-all-container">
  <div class="contact-container">
  <!--
    <div class="form-container">
      <h2>Contactez-moi</h2>
      <form class="contact-form" action="/contact" method="POST">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <div class="form-group">
          <input type="text" id="name" name="name" required>
          <label for="name" class="label-form">Quel est votre nom ?</label>
        </div>
        <div class="form-group">
          <input type="email" id="email" name="email" required>
          <label for="email" class="label-form">Quel est votre email ?</label>
        </div>
        <div class="form-group">
          <input type="text" id="subject" name="subject" required>
          <label for="subject" class="label-form">Sujet</label>
        </div>
        <div class="form-group">
          <textarea id="message" rows="5" name="content" required></textarea>
          <label for="message" class="label-form">Votre message</label>
        </div>
        <div class="form-group">
          <button type="submit" class="submit-button">Envoyer</button>
        </div>
      </form>
    </div>
    -->
    <div class="contact-details">
      <h2>Coordonnées</h2>
      <p>Email: <a href="mailto:contact@herveng.com">contact@herveng.com</a></p>
      <p>Téléphone: <a href="tel:+33665511993">+33 6 65 51 19 93</a></p>
    </div>
  </div>
</div>

app/views/posts/_post_preview.html.erb
<div class="blog-post">
  <h3 class="blog-post-title"><%= post.title %></h3>
  <p class="blog-post-excerpt"><%= post.content.truncate(150) %></p>
</div>

app/views/posts/edit.html.erb
<div class="edit-post-container">
  <h1 class="edit-post-title">Modifier l'article</h1>

  <%= form_with(model: @post) do |form| %>
    <div class="field">
      <%= form.label :title, "Titre" %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :content, "Contenu" %>
      <div class="editor"></div>
      <%= form.hidden_field :content, id: "post_content", value: @post.content %>
    </div>

    <div class="field">
      <%= form.label :cover_image, "Image de couverture" %>
      <%= form.file_field :cover_image %>
    </div>

    <div class="edit-post-buttons">
      <%= form.submit "Enregistrer les modifications", class: "edit-post-button" %>
      <%= link_to "Annuler", post_path(@post.slug), class: "edit-post-button cancel" %>
    </div>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="index-container">
  <h1 class="index-title">L'Odyssée</h1>
  <h3 class="index-subtitle">Pérégrinations et notes d'explorations</h3>

  <div class="posts">
    <% @posts.each do |post| %>
      <div class="post">
        <%= link_to post_path(post.slug) do %>
          <% if post.cover_image.attached? %>
            <%= image_tag post.cover_image, alt: post.title, class: "post-cover-image" %>
          <% end %>
          <div class="post-text">
            <h2 class="post-title"><%= post.title %></h2>
            <p class="post-content"><%= post.content.to_plain_text.truncate(100) %>
              <span class="read-more">Lire la suite</span>
            </p>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="new-post-container">
  <h1 class="new-post-title">Nouvel article</h1>

  <%= form_with(model: @post, html: { class: 'new-post-form' }) do |form| %>
    <div class="new-post-field">
      <%= form.label :cover_image, "Image de couverture", class: "new-post-label" %>
      <%= form.file_field :cover_image, class: 'new-post-input' %>
    </div>

    <div class="new-post-field">
      <%= form.label :title, "Titre", class: "new-post-label" %>
      <%= form.text_field :title, class: 'new-post-input' %>
    </div>

    <div class="new-post-field">
      <%= form.label :content, "Contenu", class: "new-post-label" %>
      <div class="editor"></div>
      <%= form.hidden_field :content, id: "post_content" %>
    </div>

    <div class="new-post-actions">
      <%= form.submit "Créer l'article", class: 'new-post-btn' %>
    </div>
  <% end %>
</div>

app/views/posts/show.html.erb
<div class="show-post-container">
  <div class="show-post-header">
    <figure class="show-post-image-container">
      <img class="show-post-image" src="<%= url_for(@post.cover_image.present? ? @post.cover_image : 'default.jpg') %>" alt="<%= @post.title %>">
    </figure>
    <h1 class="show-post-title"><%= @post.title %></h1>
  </div>
  <div class="show-post-content">
    <p><%= @post.content %></p>
  </div>
  <div class="show-post-buttons">
    <%= link_to "Revenir à la liste des articles", blog_path, class: "show-post-button" %>
    <% if user_signed_in? %>
      <%= link_to "Modifier l'article", edit_post_path(@post.slug), class: "show-post-button" %>
      <%= link_to "Supprimer l'article", post_path(@post.slug), method: :delete, data: { confirm: "Êtes-vous sûr de vouloir supprimer cet article ?" }, class: "show-post-button" %>
    <% end %>
  </div>
</div>